/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://n6wu22wmvbds5npupd22wuruxi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fl6ztf5itvg43icmrjcktk6qdi",
    "aws_cognito_identity_pool_id": "us-west-2:c622efae-f754-4f5c-9f5e-fda360b9bd78",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_VTTN8aETB",
    "aws_user_pools_web_client_id": "6ouahk8p7cv5rqmm9379p7ns5i",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
